/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_mobile_analytics_app_id": "56d3caea6b5f4e82926cd96881baa15c",
    "aws_mobile_analytics_app_region": "eu-west-2",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "56d3caea6b5f4e82926cd96881baa15c",
            "region": "eu-west-2"
        }
    },
    "aws_appsync_graphqlEndpoint": "https://vuczvd4n2bewdgycwte7x27hny.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-zgrqcp2wxvbslcfxt2mgkfag4q",
    "aws_cognito_identity_pool_id": "eu-west-2:a0a1acfa-3131-4c17-9ac7-6b025e5f4c65",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_ztC67IqIM",
    "aws_user_pools_web_client_id": "6rmk35js86ch59m85kripdv8l1",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "cheekydinoaiml135937-staging",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
